package com.money.transfer.service.exceptions;

public enum AccountErrorReason {

	ACCOUNTLOCKNOTACQUIRED,
	INSUFFICIENTAMOUNT,
	INVALIDCREDITAMOUNT,
	INVALIDDEBITAMOUNT,
	INVALIDACCOUNTDETAILS,
	DUPLICATEACCOUNTS;
}
